all functions with a comment
Ilansz/mini-projetct1-content-creators pull request #2
Opened 2019-08-01 09:30 UTC by Ilansz

2019-08-01 12:31 UTC, hugodes requested changes

2019-08-01 12:31 UTC, hugodes commented on js/game-logic.js
> +//"protecting" the game from bugs
validate input

2019-08-01 12:31 UTC, hugodes commented on js/game-logic.js
> +// Make sure the move type is rock, paper or scissors
validate move type

2019-08-01 12:31 UTC, hugodes commented on js/game-logic.js
> +// Set the winner of the round
get the winner ..

2019-09-02 08:07 UTC, Ilansz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Miniproject 2 bugs](https://trello.com/c/7lZghOuh/552-miniproject-2-bugs)

2019-09-02 09:16 UTC, merged